SECRET = 'cXbTAVLRiy6IZ9jh4VvdCzcmZBudDZir'
SALT = 'Uv588EKxd9C7i4whPLHHCyKL1CTTzmbK'
JWT_SECRET = 'hs7yJlnK7kuGD78eSYhMXZCTfP86YCev'

PG_URL = 'localhost'
PG_PORT = '5432'
PG_USER = '***'
PG_PASSWORD = '***'
PG_DATABASE = '***'

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = '***'
EMAIL_HOST_PASSWORD = '***'

EMAIL_VERIFY_EXPIRE = 600